name: language-hcl
version: '0.2.0.0'
synopsis: HCL parsers and pretty-printers for the Haskell programming language.
description: ! '
  @language-hcl@ contains HCL (Hashicorp Configuration Language) parsers and
  pretty-printers for the Haskell programming language.

  "Data.HCL" exports all the API surface in the package.
'
category: Data
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
copyright: Copyright (c) 2016 Pedro Tacla Yamada
license: MIT
github: beijaflor-io/haskell-language-hcl
extra-source-files: ./test-fixtures/*

library:
  source-dirs: src
  exposed-modules:
  - Data.HCL
  - Data.HCL.Types
  other-modules: []
  dependencies:
  - base >=4.8 && <5
  - deepseq
  - directory >=1.2.2.0
  - filepath >=1.4.0.0
  - megaparsec >= 6.2.0
  - prettyprinter >= 1.1.1
  - scientific >=0.3.4.6
  - semigroups >=0.18.1
  - text >=1.2.2.1
  - unordered-containers
  - void

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - QuickCheck
    - base
    - directory
    - filepath
    - hspec
    - language-hcl
    - megaparsec >= 6.2.0
    - hspec-megaparsec
    - prettyprinter >= 1.1.1
    - semigroups >=0.18.1
    - text
    - transformers >=0.4.2.0

benchmarks:
  hcl-benchmark:
    main: HCLBenchmark.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -threaded
    dependencies:
    - base
    - criterion
    - directory
    - filepath
    - language-hcl
    - text
